
development:
  adapter: postgresql
  database: karatedb
  pool: 5
  timeout: 5000
  username: soumitra
  password: password


test:
  adapter: postgresql

  database: karatedb

  pool: 5
  timeout: 5000
  username: soumitra
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: karatedb

  pool: 5
  timeout: 5000
  username: soumitra
  password: password

